### ISSUE TITLE
Repository out of date

### ISSUE THREAD

**Issue by dcousens** [markmarijnissen/cordova-plugin-share#8]
I see https://www.npmjs.com/package/cordova-plugin-share on `npm`,  version `0.1.3`... and it links here which is only `0.1.1`.

What is different?

**Comment by dcousens** [comment]
@markmarijnissen ?

**Comment by dcousens** [comment]
Anything?

**Comment by dcousens** [comment]
Last ping,  @markmarijnissen ?

**Comment by markmarijnissen** [comment]
I'm not maintaining this plugin anymore, as there is a much better plugin available. https://github.com/EddyVerbruggen/SocialSharing-PhoneGap-Plugin
